config/routes.rb
TSDictionary::Application.routes.draw do
  resources :vocabularies

  

end

app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
  mount_uploader :image, ImageFileUploader
  mount_uploader :pronunciation, PronunciationFileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  before_action :set_vocabulary, only: [:show, :edit, :update, :destroy]

  # GET /vocabularies
  # GET /vocabularies.json
  def index
    @vocabularies = Vocabulary.all
  end

  # GET /vocabularies/1
  # GET /vocabularies/1.json
  def show
  end

  # GET /vocabularies/new
  def new
    @vocabulary = Vocabulary.new
  end

  # GET /vocabularies/1/edit
  def edit
  end

  # POST /vocabularies
  # POST /vocabularies.json
  def create
    @vocabulary = Vocabulary.new(vocabulary_params)

    respond_to do |format|
      if @vocabulary.save
        format.html { redirect_to @vocabulary, notice: 'Vocabulary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vocabulary }
      else
        format.html { render action: 'new' }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabularies/1
  # PATCH/PUT /vocabularies/1.json
  def update
    respond_to do |format|
      if @vocabulary.update(vocabulary_params)
        format.html { redirect_to @vocabulary, notice: 'Vocabulary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabularies/1
  # DELETE /vocabularies/1.json
  def destroy
    @vocabulary.destroy
    respond_to do |format|
      format.html { redirect_to vocabularies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulary
      @vocabulary = Vocabulary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocabulary_params
      params.require(:vocabulary).permit(:word, :translated, :definition, :pronunciation, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TSDictionary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vocabularies/_form.html.erb
<%= form_for(@vocabulary) do |f| %>
  <% if @vocabulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vocabulary.errors.count, "error") %> prohibited this vocabulary from being saved:</h2>

      <ul>
      <% @vocabulary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :translated %><br>
    <%= f.text_field :translated %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :pronunciation %><br>
    <%= f.file_field :pronunciation %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vocabularies/edit.html.erb
<h1>Editing vocabulary</h1>

<%= render 'form' %>

<%= link_to 'Show', @vocabulary %> |
<%= link_to 'Back', vocabularies_path %>

app/views/vocabularies/index.html.erb
<h1>Listing vocabularies</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Translated</th>
      <th>Definition</th>
      <th>Pronunciation</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vocabularies.each do |vocabulary| %>
      <tr>
        <td><%= vocabulary.word %></td>
        <td><%= vocabulary.translated %></td>
        <td><%= vocabulary.definition %></td>
        <td><%= vocabulary.pronunciation %></td>
        <td><%= vocabulary.image %></td>
        <td><%= link_to 'Show', vocabulary %></td>
        <td><%= link_to 'Edit', edit_vocabulary_path(vocabulary) %></td>
        <td><%= link_to 'Destroy', vocabulary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vocabulary', new_vocabulary_path %>

app/views/vocabularies/new.html.erb
<h1>New vocabulary</h1>

<%= render 'form' %>

<%= link_to 'Back', vocabularies_path %>

app/views/vocabularies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @vocabulary.word %>
</p>

<p>
  <strong>Translated:</strong>
  <%= @vocabulary.translated %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @vocabulary.definition %>
</p>

<p>
  <strong>Pronunciation:</strong>
  <audio controls>
    <source src="<%= @vocabulary.pronunciation %>" type="audio/mpeg">
    Your browser does not support the audio element.
  </audio>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@vocabulary.image_url, :width => 600) if @vocabulary.image.present? %>
</p>

<%= link_to 'Edit', edit_vocabulary_path(@vocabulary) %> |
<%= link_to 'Back', vocabularies_path %>